### ISSUE TITLE
Error in compiling Scrip 

### ISSUE THREAD

**Issue by mmcintra** [SCRIP-Project/SCRIP#2]
I'm having a problem when I tried to compile SCRIP_COAWST . I'm using CentOS 6.5 , netcdf 4 , mpi , ifort .

It seems that the scprit (make) doesn't found the library LibNLM.a , any tip of how can I deal with that ?

Thank's in advance, Marcio.

**Comment by philipwjones** [comment]
Sorry - SCRIP_COAWST is unknown to me and the problem appears to be outside the SCRIP package.
