### ISSUE TITLE
Importing Scrip problem

### ISSUE THREAD

**Issue by sameerCoder** [SCRIP-Project/SCRIP#4]
Hi,
**I will really appreciate if any help**
I am getting below remapping Error
```
(pyroms1) username@username-Desktop:~/Desktop/pyroms/examples/Yellow_Sea/Inputs/Initial$ python3 cpmake_ic_file.py 
WARNING:root: scrip could not be imported. Remapping functions will not be available
Traceback (most recent call last):
  File "cpmake_ic_file.py", line 11, in <module>
    from remap import remap
  File "/home/username/Desktop/pyroms/examples/Yellow_Sea/Inputs/Initial/remap.py", line 14, in <module>
    import _remapping
ModuleNotFoundError: No module named '_remapping'
```

I have successfully installed Scrip module into my system.
Below are the command executed while installing
(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ export PREFIX=/home/username/anaconda3/envs/pyroms1
(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ make DEVELOP=1 PREFIX=$PREFIX install
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./kinds_mod.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./constants.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./iounits.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./netcdf.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./grids.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_vars.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_distwgt.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./timers.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_conserv.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_bilinear.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_bicubic.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_read.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_write.f
f2py - fcompiler=gnu95 - f90exec=gfortran - f90flags='-g -fdefault-real-8 -ffixed-form -O2 -fPIC' \
-L. -L/home/username/anaconda3/envs/pyroms1/lib -lnetcdf -lnetcdff -ljpeg -lmfhdf -ldf -lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran -I. -I/home/username/anaconda3/envs/pyroms1/include -m scrip -c kinds_mod.o constants.o iounits.o netcdf.o grids.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o remap_read.o remap.o timers.o remap_write.o ./pyscrip.f90
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands - compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands - fcompiler options
running build_src
build_src
building extension "scrip" sources
f2py options: []
f2py:> /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c
creating /tmp/tmpycsomlor/src.linux-x86_64–3.8
Reading f2cmap from '.f2py_f2cmap' …
 Mapping "integer(kind=int_kind)" to "int"
 Mapping "real(kind=dbl_kind)" to "double"
 Mapping "logical(kind=log_kind)" to "char"
Successfully applied user defined f2cmap changes
Reading fortran codes…
 Reading file './pyscrip.f90' (format:fix)
Post-processing…
 Block: scrip
 Block: compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module kinds_mod info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module constants info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module iounits info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module timers info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module grids info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_vars info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_conservative info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_distance_weight info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_bilinear info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_bicubic info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_write info used by compute_remap_weights
 Block: test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module kinds_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module constants info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module iounits info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module netcdf_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module grids info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_vars info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_read info used by test_remap_weights
 Block: remap
In: :scrip:./pyscrip.f90:remap
get_useparameters: no module kinds_mod info used by remap
In: :scrip:./pyscrip.f90:remap
get_useparameters: no module constants info used by remap
Post-processing (stage 2)…
Building modules…
 Building module "scrip"…
 Constructing wrapper function "compute_remap_weights"…
 compute_remap_weights(namelist_file)
 Constructing wrapper function "test_remap_weights"…
 test_remap_weights(namelist_file)
 Constructing wrapper function "remap"…
 remap(dst_array,map_wts,dst_add,src_add,src_array,[num_links,src_grid_size,dst_grid_size,src_grad1,src_grad2,src_grad3])
 Wrote C/API module "scrip" to file "/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c"
 adding '/tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c' to sources.
 adding '/tmp/tmpycsomlor/src.linux-x86_64–3.8' to include_dirs.
copying /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpycsomlor/src.linux-x86_64–3.8
copying /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpycsomlor/src.linux-x86_64–3.8
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler using build_ext
building 'scrip' extension
compiling C sources
C compiler: gcc -pthread -B /home/username/anaconda3/envs/pyroms1/compiler_compat -Wl, - sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
creating /tmp/tmpycsomlor/tmp
creating /tmp/tmpycsomlor/tmp/tmpycsomlor
creating /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8
compile options: '-I. -I/home/username/anaconda3/envs/pyroms1/include -I/tmp/tmpycsomlor/src.linux-x86_64–3.8 -I/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include -I/home/username/anaconda3/envs/pyroms1/include/python3.8 -c'
gcc: /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c
gcc: /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c
In file included from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.h:13,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c:16:
/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.h:13,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c:2:
/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
 ^
/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c:142:12: warning: 'f2py_size' defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, …)
 ^
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -g -fdefault-real-8 -ffixed-form -O2 -fPIC -fPIC -O3 -funroll-loops
compile options: '-I. -I/home/username/anaconda3/envs/pyroms1/include -I/tmp/tmpycsomlor/src.linux-x86_64–3.8 -I/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include -I/home/username/anaconda3/envs/pyroms1/include/python3.8 -c'
gfortran:fix: ./pyscrip.f90
./pyscrip.f90:1191:20:
grid2_count = zero
 1(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ export PREFIX=/home/username/anaconda3/envs/pyroms1
(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ make DEVELOP=1 PREFIX=$PREFIX install
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./kinds_mod.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./constants.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./iounits.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./netcdf.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./grids.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_vars.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_distwgt.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./timers.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_conserv.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_bilinear.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_bicubic.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_read.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap.f
gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -I. -I/home/username/anaconda3/envs/pyroms1/include -c ./remap_write.f
f2py - fcompiler=gnu95 - f90exec=gfortran - f90flags='-g -fdefault-real-8 -ffixed-form -O2 -fPIC' \
-L. -L/home/username/anaconda3/envs/pyroms1/lib -lnetcdf -lnetcdff -ljpeg -lmfhdf -ldf -lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran -I. -I/home/username/anaconda3/envs/pyroms1/include -m scrip -c kinds_mod.o constants.o iounits.o netcdf.o grids.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o remap_read.o remap.o timers.o remap_write.o ./pyscrip.f90
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands - compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands - fcompiler options
running build_src
build_src
building extension "scrip" sources
f2py options: []
f2py:> /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c
creating /tmp/tmpycsomlor/src.linux-x86_64–3.8
Reading f2cmap from '.f2py_f2cmap' …
 Mapping "integer(kind=int_kind)" to "int"
 Mapping "real(kind=dbl_kind)" to "double"
 Mapping "logical(kind=log_kind)" to "char"
Successfully applied user defined f2cmap changes
Reading fortran codes…
 Reading file './pyscrip.f90' (format:fix)
Post-processing…
 Block: scrip
 Block: compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module kinds_mod info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module constants info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module iounits info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module timers info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module grids info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_vars info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_conservative info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_distance_weight info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_bilinear info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_bicubic info used by compute_remap_weights
In: :scrip:./pyscrip.f90:compute_remap_weights
get_useparameters: no module remap_write info used by compute_remap_weights
 Block: test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module kinds_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module constants info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module iounits info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module netcdf_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module grids info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_vars info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_mod info used by test_remap_weights
In: :scrip:./pyscrip.f90:test_remap_weights
get_useparameters: no module remap_read info used by test_remap_weights
 Block: remap
In: :scrip:./pyscrip.f90:remap
get_useparameters: no module kinds_mod info used by remap
In: :scrip:./pyscrip.f90:remap
get_useparameters: no module constants info used by remap
Post-processing (stage 2)…
Building modules…
 Building module "scrip"…
 Constructing wrapper function "compute_remap_weights"…
 compute_remap_weights(namelist_file)
 Constructing wrapper function "test_remap_weights"…
 test_remap_weights(namelist_file)
 Constructing wrapper function "remap"…
 remap(dst_array,map_wts,dst_add,src_add,src_array,[num_links,src_grid_size,dst_grid_size,src_grad1,src_grad2,src_grad3])
 Wrote C/API module "scrip" to file "/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c"
 adding '/tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c' to sources.
 adding '/tmp/tmpycsomlor/src.linux-x86_64–3.8' to include_dirs.
copying /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/f2py/src/fortranobject.c -> /tmp/tmpycsomlor/src.linux-x86_64–3.8
copying /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/f2py/src/fortranobject.h -> /tmp/tmpycsomlor/src.linux-x86_64–3.8
build_src: building npy-pkg config files
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
Found executable /usr/bin/gfortran
customize Gnu95FCompiler using build_ext
building 'scrip' extension
compiling C sources
C compiler: gcc -pthread -B /home/username/anaconda3/envs/pyroms1/compiler_compat -Wl, - sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC
creating /tmp/tmpycsomlor/tmp
creating /tmp/tmpycsomlor/tmp/tmpycsomlor
creating /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8
compile options: '-I. -I/home/username/anaconda3/envs/pyroms1/include -I/tmp/tmpycsomlor/src.linux-x86_64–3.8 -I/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include -I/home/username/anaconda3/envs/pyroms1/include/python3.8 -c'
gcc: /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c
gcc: /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c
In file included from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.h:13,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c:16:
/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
 from /home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.h:13,
 from /tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.c:2:
/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
 ^
/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.c:142:12: warning: 'f2py_size' defined but not used [-Wunused-function]
 static int f2py_size(PyArrayObject* var, …)
 ^
compiling Fortran sources
Fortran f77 compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops
Fortran f90 compiler: gfortran -g -fdefault-real-8 -ffixed-form -O2 -fPIC -fPIC -O3 -funroll-loops
Fortran fix compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -g -fdefault-real-8 -ffixed-form -O2 -fPIC -fPIC -O3 -funroll-loops
compile options: '-I. -I/home/username/anaconda3/envs/pyroms1/include -I/tmp/tmpycsomlor/src.linux-x86_64–3.8 -I/home/username/anaconda3/envs/pyroms1/lib/python3.8/site-packages/numpy/core/include -I/home/username/anaconda3/envs/pyroms1/include/python3.8 -c'
gfortran:fix: ./pyscrip.f90
./pyscrip.f90:1191:20:
grid2_count = zero
 1
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
/usr/bin/gfortran -Wall -g -Wall -g -shared /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.o /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.o /tmp/tmpycsomlor/pyscrip.o kinds_mod.o constants.o iounits.o netcdf.o grids.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o remap_read.o remap.o timers.o remap_write.o -L. -L/home/username/anaconda3/envs/pyroms1/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -lnetcdf -lnetcdff -ljpeg -lmfhdf -ldf -lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran -lgfortran -o ./scrip.cpython-38-x86_64-linux-gnu.so
Removing build directory /tmp/tmpycsomlor
cp -vf scrip*.so ../../../pyroms
'scrip.cpython-38-x86_64-linux-gnu.so' -> '../../../pyroms/scrip.cpython-38-x86_64-linux-gnu.so'
(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ mv -vf scrip*.so ../../../pyroms
'scrip.cpython-38-x86_64-linux-gnu.so' -> '../../../pyroms/scrip.cpython-38-x86_64-linux-gnu.so'
Warning: Possible change of value in conversion from REAL(8) to INTEGER(4) at (1) [-Wconversion]
/usr/bin/gfortran -Wall -g -Wall -g -shared /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8/scripmodule.o /tmp/tmpycsomlor/tmp/tmpycsomlor/src.linux-x86_64–3.8/fortranobject.o /tmp/tmpycsomlor/pyscrip.o kinds_mod.o constants.o iounits.o netcdf.o grids.o remap_vars.o remap_distwgt.o remap_conserv.o remap_bilinear.o remap_bicubic.o remap_read.o remap.o timers.o remap_write.o -L. -L/home/username/anaconda3/envs/pyroms1/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5 -lnetcdf -lnetcdff -ljpeg -lmfhdf -ldf -lhdf5 -lhdf5_fortran -lhdf5_hl -lhdf5hl_fortran -lgfortran -o ./scrip.cpython-38-x86_64-linux-gnu.so
Removing build directory /tmp/tmpycsomlor
cp -vf scrip*.so ../../../pyroms
'scrip.cpython-38-x86_64-linux-gnu.so' -> '../../../pyroms/scrip.cpython-38-x86_64-linux-gnu.so'
(pyroms1) username@username-Desktop:~/Desktop/pyroms/pyroms/external/scrip/source$ mv -vf scrip*.so ../../../pyroms
'scrip.cpython-38-x86_64-linux-gnu.so' -> '../../../pyroms/scrip.cpython-38-x86_64-linux-gnu.so'

**Comment by philipwjones** [comment]
Sorry, this script is outside the SCRIP package and I have no idea how it's been integrated. Looks like you need to contact someone from pyroms
